# Generated by Django 3.0 on 2020-11-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_fb', models.CharField(blank=True, max_length=100, null=True)),
                ('artist_twitter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('cast_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=100)),
                ('label_youtube_channel_link', models.CharField(max_length=100)),
                ('label_fb_page_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=255, unique=True)),
                ('video_details', models.TextField()),
                ('youtube_link', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('cast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_cast', to='media_app.Cast')),
                ('lebel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='media_app.Label')),
                ('video_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director', to='media_app.Artist')),
                ('video_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='media_app.Artist')),
                ('video_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.VideoType')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=255, unique=True)),
                ('youtube_link', models.CharField(blank=True, max_length=100, null=True)),
                ('song_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_director', to='media_app.Artist')),
                ('song_lyricist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_lyricist', to='media_app.Artist')),
                ('song_music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_music', to='media_app.Artist')),
                ('song_writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_writer', to='media_app.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='CastByArtish',
            fields=[
                ('cast_by_artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='media_app.Artist')),
                ('cast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_app.Cast')),
            ],
        ),
    ]
